width = 15
height = 15
mode = "clear" # sight, poly, halo, clear
ai = 2
allai = False
players = 3
Map = "random" # "random", "generated" or specific name (e.g. "lakes")
mapType = "towns" # "regular", "any" or "small"
AltPictures = False
